### PR TITLE
Add nulladmin1

### PR DESCRIPTION
**Pull request by nulladmin1**
## My Rice
Wakatime badge

- How many hours did it take to write this: `30`

- Source Code: `https://github.com/nulladmin1/nixos-config`
  
  
  
- Screenshots of your rice
Image 1
Image 2

  
  
  

## Checklist

- [x] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
please link you hackatime badge!!

**Comment by nulladmin1** [comment]
> please link you hackatime badge!!

Okay I did

**Review by NeonGamerBot-QK — APPROVED** [review]
lgtm

**Comment by NeonGamerBot-QK** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
