### PR TITLE
Added my Beach Bunny Theme

### PR DESCRIPTION
**Pull request by BoomBoomMushroom**
## Beach Bunny Theme

https://waka.hackclub.com/api/badge/U07DM4LDW7N/interval:any/project:DillionRice-LinuxMint
image

- How many hours did it take to write this: `4 hours`

- Source Code: `https://github.com/BoomBoomMushroom/DillionRice-LinuxMint`
  
  
  
  
  
image

## Extra Comments

Hello person who receives the forms,
I plan to get the Thigh highs, and if so please let them be pastel pink! Pink is my favorite color.
Yours truly, BoomBoomMushroom

## Checklist

- [x] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Comment by BoomBoomMushroom** [comment]
Hello person who receives the forms,
I plan to get the Thigh highs, and if so please let them be pastel pink! Pink is my favorite color.
Yours truly, BoomBoomMushroom

**Comment by webbrowser11** [comment]
that's a bot man...

**Comment by BoomBoomMushroom** [comment]
> that's a bot man...
Well, it couldn't hurt to try.

**Comment by webbrowser11** [comment]
bruv

**Comment by webbrowser11** [comment]
oh well... wait till someone with "escalated privileges" merges your pr i guess.

**Comment by V205Arduino** [comment]
I took a look at the form from other closed PRs, and I don't see an option to select color.
Would be interesting it if was available though 👀

**Comment by BoomBoomMushroom** [comment]
Yeah I heard in the slack that there were three colors (black, pink, and some thing else). And since I didn't see it in the form I might as well try and say it here

**Comment by OtterCodes101** [comment]
the colors will most likely be random.

**Review by OtterCodes101 — APPROVED** [review]
LGTM!

**Comment by OtterCodes101** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
