### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by leanghok120**
## Leanghok Cozy Gruvbox

[image](https://waka.hackclub.com/api/badge/U08047XUWNR/interval:any/project:dots)

- How many hours did it take to write this: `4` (4 because I did this rice before joining hackclub)

- Source Code: `https://github.com/leanghok120/Dotfiles`

- Screenshots of your rice

image

image

## Checklist

- [x] I have filled out the form correctly

- [x] I have my PR labeled correctly

- [x] I have not already submitted a rice

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
please comment your hacktime svg url in the pr.

**Comment by leanghok120** [comment]
> please comment your hacktime svg url in the pr.

How do i get that svg?

**Comment by NeonGamerBot-QK** [comment]
> > please comment your hacktime svg url in the pr.
> 
> How do i get that svg?

waka.hackclub.com > projects > (your rice name) > right click on the img badge > click "Open image in new tab" > copy and paste url here.

**Comment by leanghok120** [comment]
> > > please comment your hacktime svg url in the pr.
> > 
> > 
> > How do i get that svg?
> 
> waka.hackclub.com > projects > (your rice name) > right click on the img badge > click "Open image in new tab" > copy and paste url here.

Done

**Review by NeonGamerBot-QK — APPROVED** [review]
lgtm

**Comment by NeonGamerBot-QK** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
