### PR TITLE
added my dotfiles repo

### PR DESCRIPTION
**Pull request by GearBoxFox**
## Neon Rowan Evangelion

https://waka.hackclub.com/summary?project=awesome

https://waka.hackclub.com/api/badge/U062Z8FQA6S/interval:any/project:awesome

- Just over 9 hours spent writing this awesomewm config from scratch

- Source Code: `https://github.com/GearBoxFox/dotfiles`
- Screenshots of your rice
image
image

## Extra Comments
- The wakatime badge seems to be broken, so I included the actual link to my wakatime project. If needed I can also send screenshots
- I'm planning on adding additional content at some point, including a dock, app rules, and a sidebar

## Checklist

- [ ] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
please embed the wakatime badge here

**Comment by GearBoxFox** [comment]
I have the link in the PR, but even with the ![image] tag it's not showing as an image.

**Comment by NeonGamerBot-QK** [comment]
you will have to make your badge public for me to verify your hours. you can do this in hacktime settings.

**Comment by GearBoxFox** [comment]
All the options in the hackatime permissions are now set to public.

**Review by NeonGamerBot-QK — APPROVED** [review]
lgtm, (please embed your badge in ur original message if u dont it will still get merged)

**Comment by NeonGamerBot-QK** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
