### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by FluxC0**
## My Rice
image
image
> [!NOTE]
> The first badge doesn't show up properly, but it reads 28 minutes.

- How many hours did it take to write this: 1`

- Source Code: `https://github.com/fluxc0/therealdots`

- Screenshots of your rice
 
image

## Checklist

- [ !] I have filled out the form correctly
- [ !] I have my PR labeled correctly
- [ !] I have not already submitted a rice
- [ !] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Comment by FluxC0** [comment]
Note: i did spend more time on this but i forgot hackatime for a bit

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
Please get the correct image url
( read the PR comments inside the first message)

**Comment by FluxC0** [comment]
okie, one second

**Comment by FluxC0** [comment]
@NeonGamerBot-QK Got it !

**Review by NeonGamerBot-QK — APPROVED** [review]
Lgtm

**Pull request merged**
