### PR TITLE
Added Mei Misaki My Beloved to members.json

### PR DESCRIPTION
**Pull request by Circuitbreaker08**
## Mei Misaki My Beloved

https://waka.hackclub.com/api/badge/U081686E34P/interval:any/project:Mei-Misaki-My-Beloved

- How many hours did it take to write this: `>0.5 logged (another hour got filed under unknown); About a week for total work (install, research, other config outside of Code)`

- Source Code: `https://github.com/Circuitbreaker08/Mei-Misaki-My-Beloved/tree/main`
  
  
  
  
  

image
image
image
image

## Extra Comments
Eyepatch anime girls for life!
## Checklist

- [x] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Comment by NeonGamerBot-QK** [comment]
Um @OtterCodes101  up to u

**Comment by Circuitbreaker08** [comment]
Note: my project just showed up in Hackatime im going to update my stuffs rq

**Comment by Circuitbreaker08** [comment]
New badge is in

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
Fix badge

**Comment by NeonGamerBot-QK** [comment]
Your badge isn’t public please make it public

**Comment by Circuitbreaker08** [comment]
I made it public, but when checking unauthenticated I get yelled at for `requested time range too broad`

**Comment by Circuitbreaker08** [comment]
Ok i made it stop yelling at me

**Review by NeonGamerBot-QK — APPROVED** [review]
Lgtm

**Comment by NeonGamerBot-QK** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
