### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by udontur**
## UdonTur's Productivity Rice

- How many hours did it take to write this: `2+` (Recorded on Hakatime only, see Extra Comments) 

- Source Code: `https://github.com/udontur/hyprland`
  
  
  

- Screenshots of your rice
[Watch the Demo](https://cloud-2imm1v6lb-hack-club-bot.vercel.app/0hyprland-showcase.mp4)

## Extra Comments
I spent most of the time ricing this config before I joined Hackclub. Hence, many hours were not logged. I probably used more than `8+` hours ricing it (not include working around and learn with arch)

## Checklist
- [ ] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
I need ur hacktime badge please!

**Comment by udontur** [comment]
Sorry, my bad! I have just added the badge. Thanks

**Review by NeonGamerBot-QK — APPROVED** [review]

**Comment by NeonGamerBot-QK** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Comment by udontur** [comment]
Thank you and Hack Club for the socks!

**Pull request merged**
