### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by Hibernathan1212**
## Fedora Hyprland

- Slack ID: U082JK5ERFB
- How many hours did it take to write this: `~1.2`
- https://waka.hackclub.com/summary?interval=any&project=Documents
- https://waka.hackclub.com/summary?interval=any&project=nathan
- https://waka.hackclub.com/summary?interval=any&project=welcome

- Source Code: `https://github.com/Hibernathan1212/dotfiles`
  
  
  
  
  

Screenshot 2024-12-24 at 9 24 31 PM

Screenshot 2024-12-23 at 4 46 03 PM

Screenshot 2024-12-24 at 9 28 25 PM

## Checklist

- [x] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
Can i have your slack user ID please!

**Comment by Hibernathan1212** [comment]
Slack ID: U082JK5ERFB

**Review by NeonGamerBot-QK — APPROVED** [review]
lgtm, checked via script

**Comment by NeonGamerBot-QK** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
