### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by Cyclic007**
## Cyclic-Arch-Rice

https://waka.hackclub.com/api/badge/Cyclic/interval:any/project:.config

- How many hours did it take to write this: `4`

- Source Code: `https://github.com/Cyclic007/Arch-Rice/tree/main`
  
  
  
  
  
20241125_05h11m40s_grim

## Extra Comments
the wakatime was split up and some was lost

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
make your badge public please :D

**Comment by OtterCodes101** [comment]
it is public but it says `requested time range too broad`

**Comment by Cyclic007** [comment]
what does that mean

**Comment by Cyclic007** [comment]
because it works for me

**Review by NeonGamerBot-QK — APPROVED** [review]

**Comment by OtterCodes101** [comment]
oh it works now

**Comment by OtterCodes101** [comment]
coulda sworn I put it here

**Pull request merged**
