### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by TheTridentGuy**
## Raspbian Rice

https://waka.hackclub.com/api/badge/U06FG6G6SNL/interval:high_seas/project:RaspbianRice
- How many hours did it take to write this: `4`
- https://waka.hackclub.com/api/badge/U06FG6G6SNL/interval:high_seas/project:RaspbianRice

- Source Code: `https://github.com/TheTridentGuy/RaspbianRice/`
  
  
  
  
  

## Checklist

- [x] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
Please opt in on wakatime to share project stats

**Comment by OtterCodes101** [comment]
you need to opt in to entry-specific data

**Comment by TheTridentGuy** [comment]
I think I might have?

**Comment by NeonGamerBot-QK** [comment]
still no working badge

**Comment by OtterCodes101** [comment]
femboy flag :3c

**Pull request merged**
