### PR TITLE
Hyprppuccin

### PR DESCRIPTION
**Pull request by Iris-TheRainbow**
## Hyprppuccin

-How many hours did it take to write this: `1.25`

image

- Source Code: `https://github.com/Iris-TheRainbow/dotfiles`

- Screenshots of my rice
image
image

## Extra Comments
This uses the Catppuccin Macchiato colors, mostly in teal, but I did lots of the theming myself, or heavily modified public Catppuccin themes

## Checklist
- [x] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
Make the badge public please

**Comment by OtterCodes101** [comment]
you need to opt in to entry-specific data

**Comment by Iris-TheRainbow** [comment]
@NeonGamerBot-QK Mb! Fixed
image

**Review by OtterCodes101 — APPROVED** [review]
LGTM

**Comment by OtterCodes101** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
