### PR TITLE
Add askiiart to members.json

### PR DESCRIPTION
**Pull request by askiiart**
## rice rice oooooo i sure do love cheesey rice

- How many hours did it take to write this: `1.66666667` i guess
- Source Code: `https://github.com/askiiart/dotfiles`
- Screenshots of your rice
A screenshot of fastfetch (like neofetch) running with these dotfiles

## Checklist

- [✅] I have filled out the form correctly

- [✅] I have my PR labeled correctly

- [✅] I have not already submitted a rice

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
please comment your hacktime svg url in the pr.
to get them follow the steps below:
> waka.hackclub.com > projects > (your rice name) > right click on the img badge > click "Open image in new tab" > copy and paste url here.

**Comment by askiiart** [comment]
Alright, there we go: `https://waka.hackclub.com/api/badge/U080M3QHFC1/interval:any/project:dotfiles`

wakatime svg

**Comment by askiiart** [comment]
Not sure how this is supposed to go, though; testing it in an incognito window returns error 403:

> requested time range too broad

So I'm not sure how that's supposed to be used here

**Comment by NeonGamerBot-QK** [comment]
can you please try embeding it like done in the other PR's

**Comment by askiiart** [comment]
Oh alright, I misinterpreted it. Here's the thing:
project_dotfiles

**Review by NeonGamerBot-QK — APPROVED** [review]
lgtm

**Comment by OtterCodes101** [comment]
looks all good to me!

**Pull request merged**
