### PR TITLE
Add cyao's rice

### PR DESCRIPTION
**Pull request by cheyao**
## Cyao's rice

- How many hours did it take to write this: `7.9`
https://waka.hackclub.com/api/badge/U07EQJY9YDD/interval:high_seas/project:hypr

- Source Code: `https://github.com/cheyao/hyprland`
  
  
  

  
  
  

## Checklist

- [x] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Comment by OtterCodes101** [comment]
on hackatime, you need to opt in to  entry specific data

**Comment by cheyao** [comment]
I just oped in! Don't know why the badge is only displaying 5 hrs. On high seas it's 7.9hrs
image
And on the dashboard it's 8hrs
image

**Review by OtterCodes101 — APPROVED** [review]
looks good to me!

**Comment by OtterCodes101** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
