### PR TITLE
noahPink

### PR DESCRIPTION
**Pull request by PGtheVRguy**
## My Rice

- How many hours did it take to write this: 1`x amount of hours here (e.g: 4)`

- Source Code: https://github.com/PGtheVRguy/hackClubWinter/tree/main/ricathon `https://github.com/OtterCodes101/dotfiles`
  
  
  
  
  
my_desktop
Screenshot_from_2024-11-15_17-35-45

## Extra Comments

It makes it so the basic environment is a *little* more pink. This is my first experiment with the themes and I think this is a good start!

## Checklist

- [x] I have filled out the form correctly

- [x] I have my PR labeled correctly

- [x] I have not already submitted a rice

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
please comment your hacktime svg url in this pr.

**Comment by PGtheVRguy** [comment]
What do you mean by hackclub svg url? Is this something in the hackatime site?

**Comment by NeonGamerBot-QK** [comment]
waka.hackclub.com > projects > (your rice name) > right click on the img badge > click "Open image in new tab" > copy and paste url here.

**Comment by PGtheVRguy** [comment]
https://waka.hackclub.com/api/badge/U078WRXU7B9/interval:any/project:lmtheme
Is this it?

**Comment by NeonGamerBot-QK** [comment]
please embed it as an image

**Comment by PGtheVRguy** [comment]
image
Does this work? Sorry it still just shows up as a link in the Preview tab. I saved the image directly and dragged and dropped it in too, that is this:
project_lmtheme

**Review by NeonGamerBot-QK — APPROVED** [review]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
