### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by yoavmlotok**
## Cat Rice

badge?

- How many hours did it take to write this: `5+ hours (time is a bit inaccurate)`
- Source Code: `https://github.com/yoavmlotok/cat-rice`
- Screenshots:
preview

## Checklist

- [✓] I have filled out the form correctly
- [✓] I have my PR labeled correctly
- [✓] I have not already submitted a rice
- [✓] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Comment by yoavmlotok** [comment]
why fail :3c

**Review by NeonGamerBot-QK — DISMISSED** [review]
conflicts
> sorry for not reviewing earlier i have been busy

**Comment by yoavmlotok** [comment]
god dammit

**Comment by yoavmlotok** [comment]
I don't get why it is still failinggg

**Comment by NeonGamerBot-QK** [comment]
ignore prettier failing

**Comment by NeonGamerBot-QK** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
