### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by Volkov08**
i love NMS (first rice ig)

https://waka.hackclub.com/api/badge/U0820V84P6Z/interval:high_seas/project:Riceathon

- How many hours did it take to write this: `2 1/2`

- Source Code: `https://github.com/Volkov08/firstricedots/`
  
  
  
screenshot
  
  

## Checklist

- [ x] I have filled out the form correctly
- [ x] I have my PR labeled correctly
- [x ] I have not already submitted a rice
- [ x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
Invalid hacktime badge, please make it public

**Comment by Volkov08** [comment]
mb, changed the settings, now it should be available.
also changed the interval of the link because i accidentally selected today before, now it shows the entire coding duration from yesterday

**Comment by Volkov08** [comment]
also why of all things is prettier failing

**Review by NeonGamerBot-QK — APPROVED** [review]

**Comment by NeonGamerBot-QK** [comment]
dw about that

**Comment by Volkov08** [comment]
yall will probably be shipping from USA, right?

**Comment by OtterCodes101** [comment]
correct

**Pull request merged**
