### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by Swarsin**
## Swarsin's Rice

https://waka.hackclub.com/api/badge/U079ASWN7P1/interval:today/project:WorkTracker

- How many hours did it take to write this: `3`ish

- Source Code: `https://github.com/Swarsin/dotfiles`

- Screenshots of your rice
image
image
2024-11-28-184046_hyprshot

## Extra Comments
3rd pic is the swww transition animation when changing wallpapers!

## Checklist
- [X] I have filled out the form correctly
- [X] I have my PR labeled correctly
- [X] I have not already submitted a rice
- [X] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
please fix ur hackatime badge!

**Comment by Swarsin** [comment]
Hi 
this is the badge:
https://waka.hackclub.com/api/badge/U079ASWN7P1/interval:yesterday/project:WorkTracker
image

**Review by NeonGamerBot-QK — APPROVED** [review]
Lgtm

**Comment by OtterCodes101** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
