### PR TITLE
added my dotfiles 

### PR DESCRIPTION
**Pull request by StatusCritical**
## Miku i3

wakatime badge

- How many hours did it take to write this: about 7 of me being active, the rest was pushing files

- Source Code: `https://github.com/StatusCritical/.config`
  
  
  
  
  
Screenshot 2024-11-17 192355

## Extra Comments
sorry if this is a little messed up, not a lot to compare against right now.
## Checklist

- [x] I have filled out the form correctly
- [x] I have my PR labeled correctly
- [x] I have not already submitted a rice
- [x] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
please make your badge public

**Comment by StatusCritical** [comment]
how would i make it public?

**Review by OtterCodes101 — APPROVED** [review]
LGTM!

**Comment by OtterCodes101** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Pull request merged**
