### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by ashheartz**
## I3 Rice

- How many hours did it take to write this: `[1h51m](https://waka.hackclub.com/api/badge/U085HGVQE9F/interval:any/project:ashie)`

- Source Code: `https://github.com/ashheartz/i3rice/`
  
  
  
  
  

## Checklist

- [X] I have filled out the form correctly
- [X] I have my PR labeled correctly
- [X] I have not already submitted a rice
- [X] Under the section where it states "How many hours did it take to write this:" I have a valid image link

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
invalid hacktime badge

**Comment by ashheartz** [comment]
> invalid hacktime badge

I didn't see an img badge, so I just put my info into the url example, where is the badge?

**Comment by ashheartz** [comment]
> invalid hacktime badge

Fixed it

**Review by NeonGamerBot-QK — APPROVED** [review]

**Comment by NeonGamerBot-QK** [comment]
Hi! please stop making and closing PR's

**Comment by ashheartz** [comment]
> Hi! please stop making and closing PR's

My bad, sorry

**Comment by NeonGamerBot-QK** [comment]
im sorry for merging this very late; i was busy

**Comment by NeonGamerBot-QK** [comment]
👋 Thanks for your PR!
To claim your free socks fill out this [form](https://forms.hackclub.com/t/joD554Crhsus)

**Comment by ashheartz** [comment]
> im sorry for merging this very late; i was busy

dw abt it lol

**Pull request merged**
